version: '3.8'

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8282:8282" # Forward the exposed port 8282 on the container to port 8282 on the host machine (left side is host, right side is container)
    volumes:
      - ./API:/app
    environment:
      - ENV=production

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - ./front:/app
    environment:
      - ENV=production