definitions:
  dashboard_structs.Challenge:
    properties:
      description:
        type: string
      difficulty:
        type: string
      id:
        type: integer
      illustration_filename:
        type: string
      lore_for_player:
        type: string
      name:
        type: string
      osint_data:
        type: string
      session_key:
        type: string
      status:
        type: string
    type: object
  dashboard_structs.Dashboard:
    description: Structure contenant le dashboard de l'utilisateur
    properties:
      challenges:
        items:
          $ref: '#/definitions/dashboard_structs.Challenge'
        type: array
      score:
        type: integer
    type: object
  profiles_handling.Response:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  registering.Registering_response:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  sessions.Session_creation_response:
    properties:
      message:
        type: string
      session_key:
        type: string
    type: object
  sessions_structs.Chall_message:
    properties:
      gave_contact:
        type: boolean
      gave_hint:
        type: boolean
      message:
        type: string
      session_character_id:
        type: string
      timestamp:
        type: string
      user_or_character:
        type: string
    type: object
  sessions_structs.Create_session_request:
    properties:
      title:
        type: string
    type: object
  sessions_structs.Post_session_data_request:
    properties:
      character_name:
        type: string
      message:
        type: string
    type: object
  sessions_structs.Session:
    properties:
      challenge_id:
        type: integer
      characters:
        items:
          $ref: '#/definitions/sessions_structs.Session_character'
        type: array
      hints:
        items:
          $ref: '#/definitions/sessions_structs.Session_hint'
        type: array
      id:
        type: integer
      messages:
        items:
          $ref: '#/definitions/sessions_structs.Session_message'
        type: array
      session_key:
        type: string
      start_time:
        type: string
      status:
        type: string
      user_id:
        type: integer
    type: object
  sessions_structs.Session_character:
    properties:
      advice_to_user:
        type: string
      character_id:
        type: integer
      communication_type:
        type: string
      current_suspicion:
        type: integer
      holds_hint:
        type: boolean
      id:
        type: integer
      is_accessible:
        type: boolean
      name:
        type: string
      osint_data:
        type: string
      session_id:
        type: integer
      title:
        type: string
    type: object
  sessions_structs.Session_hint:
    properties:
      hint_id:
        type: integer
      id:
        type: integer
      illustration_type:
        type: string
      is_available:
        type: boolean
      is_capital:
        type: boolean
      mentions:
        type: integer
      session_id:
        type: integer
      text:
        type: string
      title:
        type: string
    type: object
  sessions_structs.Session_message:
    properties:
      contact_given:
        type: boolean
      hint_given:
        type: boolean
      id:
        type: integer
      message:
        type: string
      sender:
        description: '''user'' or ''character'''
        type: string
      session_character_id:
        type: integer
      timestamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/dashboard:
    get:
      consumes:
      - application/json
      description: Gère les requêtes pour récupérer les données du tableau des challenges
        de la page principale.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dashboard_structs.Dashboard'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Dashboard handler
      tags:
      - Dashboard
      - Challenges
  /api/sessions/{session_id}:
    get:
      consumes:
      - application/json
      description: Récupère les données de la session en cours à partir de l'ID de
        session (chaine de 6 caractères aléatoires) et renvoie les données du challenge
        en JSON
      parameters:
      - description: ID de session (chaine de 6 caractères aléatoires)
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Session data retrieved successfully
          schema:
            $ref: '#/definitions/sessions_structs.Session'
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Session not found
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - socengai-username: []
      - socengai-auth: []
      summary: Récupère les données de la session en cours
      tags:
      - sessions
      - challenges
      - game
      - api
  /api/sessions/{session_key}:
    post:
      consumes:
      - application/json
      description: Envoie les données de session (message de l'utilisateur et réponse
        de l'IA) à la base de données
      parameters:
      - description: Clé de session (chaine de 6 caractères aléatoires)
        in: path
        name: session_key
        required: true
        type: string
      - description: Message de l'utilisateur et nom du personnage
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sessions_structs.Post_session_data_request'
      produces:
      - application/json
      responses:
        "200":
          description: Session data posted successfully
          schema:
            $ref: '#/definitions/sessions_structs.Chall_message'
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - socengai-username: []
      - socengai-auth: []
      summary: Envoie les données de session (message de l'utilisateur et réponse
        de l'IA) à la base de données
      tags:
      - sessions
      - challenges
      - game
      - api
  /create-user:
    post:
      consumes:
      - application/json
      description: Créer un nouvel utilisateur avec les informations fournies
      parameters:
      - description: Nom d'utilisateur de l'utilisateur
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Mot de passe de l'utilisateur
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Email de l'utilisateur
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/registering.Registering_response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/registering.Registering_response'
      summary: Créer un nouvel utilisateur
      tags:
      - registering
      - users
      - authentication
  /edit-profile:
    put:
      consumes:
      - application/json
      description: Éditer le profil de l'utilisateur avec les informations fournies
      parameters:
      - description: Nom d'utilisateur de l'utilisateur
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Biographie de l'utilisateur
        in: body
        name: biography
        required: true
        schema:
          type: string
      - description: Avatar de l'utilisateur (URL ou chemin d'accès)
        in: body
        name: avatar
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Profile updated successfully
          schema:
            $ref: '#/definitions/profiles_handling.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - socengai-username: []
      - socengai-auth: []
      summary: Éditer le profil de l'utilisateur (nom d'utilisateur, biographie, avatar)
      tags:
      - profiles
      - users
      - authentication
      - edit
      - profile
      - avatar
      - biography
      - username
  /edit-user:
    put:
      consumes:
      - application/json
      description: Éditer les informations sensibles de l'utilisateur avec les informations
        fournies
      parameters:
      - description: Nouvel email de l'utilisateur
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Mot de passe actuel de l'utilisateur
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Nouveau mot de passe de l'utilisateur
        in: body
        name: newpassword
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: User updated successfully
          schema:
            $ref: '#/definitions/profiles_handling.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - socengai-username: []
      - socengai-auth: []
      summary: Éditer les informations sensibles de l'utilisateur (email, mot de passe)
      tags:
      - profiles
      - users
      - authentication
      - edit
      - profile
      - email
      - password
  /start-challenge:
    post:
      consumes:
      - application/json
      description: Gère les requêtes pour initier une session de jeu à partir du nom
        d'un challenge.
      parameters:
      - description: Nom du challenge à partir duquel on veut créer une session de
          jeu
        in: body
        name: challenge_name
        required: true
        schema:
          $ref: '#/definitions/sessions_structs.Create_session_request'
      produces:
      - application/json
      responses:
        "200":
          description: Session created successfully
          schema:
            $ref: '#/definitions/sessions.Session_creation_response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sessions.Session_creation_response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/sessions.Session_creation_response'
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - socengai-username: []
      - socengai-auth: []
      summary: Handler des sessions
      tags:
      - sessions
      - challenges
      - game
      - api
swagger: "2.0"
